name: kohi-psql

services:
  db:
    # psql --pset=pager=off -d kohi -U kohi -W
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: kohi
      POSTGRES_DB: kohi
    ports:
      - 5432:5432
    volumes:
      - type: bind 
        source: ./db
        target: /docker-entrypoint-initdb.d  
        
  # server:
  #   image: postgrest/postgrest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgres://postgres:1234@db:5432/kohi
  #     # PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
  #   volumes:
  #     - ./config/postgrest.conf:/etc/postgrest.conf
  #   depends_on:
  #     - db 
        
  adminer:
    # Dang nhap tren web: localhost:8080
    # System: PostgreSQL
    # Server: postgres
    # Username: kohi
    # Database: kohi
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - 8080:8080
    